---
#
# EECS 4287/5287: Principles of Cloud Computing
# Author: Aniruddha Gokhale
# Created: Fall 2016
# Modified: Fall 2018
# Modified: Fall 2020
# Updated : Fall 2022 Vikash Singh

# In this playbook, we will show how to remove an installed package via
# the aptitude module
#
- hosts: MyChamVMs          # specified in the MyInventory file
  remote_user: cc         # note that the user is cc for the
                             # chameleon VM else use the
                             # appropriate user name

  tasks:                     # the task to be performed
  - name: Remove the installed subversion module using apt-get
    apt: name=subversion state=absent purge=yes
                     # by making state=absent, we imply remove
                     # by saying purge=yes, all config files are removed 
    become: yes     # run with "sudo" privileges
...